const ACTION_TYPES = {
  // CREATE_CONTACT: 'CREATE_CONTACT',
  CREATE_CONTACT_ACTION: 'CREATE_CONTACT_ACTION', // Загрузить
  CREATE_CONTACT_REQUEST: 'CREATE_CONTACT_REQUEST', // Гружу
  CREATE_CONTACT_SUCCESS: 'CREATE_CONTACT_SUCCESS', // Пришли данные
  CREATE_CONTACT_ERROR: 'CREATE_CONTACT_ERROR', // Пришла ошибка

  GET_CONTACTS_ACTION: 'GET_CONTACTS_ACTION',
  GET_CONTACTS_REQUEST: 'GET_CONTACTS_REQUEST',
  GET_CONTACTS_SUCCESS: 'GET_CONTACTS_SUCCESS',
  GET_CONTACTS_ERROR: 'GET_CONTACTS_ERROR',

  //UPDATE_CONTACT: 'UPDATE_CONTACT',
  UPDATE_CONTACT_ACTION: 'UPDATE_CONTACT_ACTION',
  UPDATE_CONTACT_REQUEST: 'UPDATE_CONTACT_REQUEST',
  UPDATE_CONTACT_SUCCESS: 'UPDATE_CONTACT_SUCCESS',
  UPDATE_CONTACT_ERROR: 'UPDATE_CONTACT_ERROR',

  REMOVE_CONTACT: 'REMOVE_CONTACT',

  UPDATE_FILTER: 'UPDATE_FILTER',
};

export default ACTION_TYPES;
